Sprint 4
MaximStovba/middle.messenger.praktikum.yandex pull request #5
Opened 2022-01-22 14:54 UTC by MaximStovba

2022-01-23 21:29 UTC, DmitryKhitrin requested changes
Привет, спасибо за вашу работу, по коду все выглядит очень хорошо, особенно после рефакторинга типов, но есть пара вещей, которые хотелось бы поправить:

- давайте попробуем сделать работу чуть проще и заиспользуем docker образ с предустановленным nodejs, который поддерживает официальная команда ноды)
- по ссылке на heroku проект не открывается, отдается 500

2022-01-23 21:29 UTC, DmitryKhitrin commented on src/pages/chat/components/chat-card/chat-card.ts
> +const imgUrl =
```suggestion
const profilePhotoUrl =
```

2022-01-23 21:29 UTC, DmitryKhitrin commented on Dockerfile
> +FROM ubuntu:latest
Конечно можно собирать образ рукам, но гораздо удобней использовать контейнер, где уже стоит nodejs нужной версии со всеми зависимостями) https://hub.docker.com/_/node

2022-01-25 19:59 UTC, MaximStovba commented on Dockerfile
> +FROM ubuntu:latest
Исправил

2022-01-25 19:59 UTC, MaximStovba commented on src/pages/chat/components/chat-card/chat-card.ts
> +const imgUrl =
Исправил

2022-01-25 20:11 UTC, MaximStovba commented
Привет, спасибо за обратную связь. Исправления внес. Ссылку на Heroku проверил, она рабочая. В документах Heroku обнаружил, что когда используется free доступ, если dyno не используется некоторое время (30 минут), он выключается. После первая загрузка длится порядка 20-30 секунд (приложение не отвечает), далее все грузится нормально.

2022-01-26 07:46 UTC, DmitryKhitrin approved these changes
Спасибо за внесенные правки, работу принимаю. Дальше только интересней!)

2022-01-28 13:32 UTC, merged